name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build project
        run: pnpm run build

      - name: Run tests (if available)
        run: |
          if pnpm run test --help >/dev/null 2>&1; then
            pnpm run test
          else
            echo "No test script found, skipping tests"
          fi

      - name: Check build size
        run: |
          echo "Build completed successfully!"
          du -sh dist/
          echo "Build artifacts:"
          ls -la dist/
